<?php

namespace app\admin\controller;

use app\common\model\AuthGroup;
use app\common\model\Rule;
use think\Controller;

class Group extends Common
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new AuthGroup();
    }

    public function rule(){
        if(request()->isPost()){
            $rules=$this->db->find(input('post.id'));
            $rule = explode(",", $rules['rules']);
            $data=ctree((new Rule())->select(),'pid',0,'open',$rule);
            return $data;
        }
        $id=request()->get('id');
        if($id){
            $data=$this->db->find($id);
            $this->assign('data',$data);
        }
        return view();
    }

    public function index(){
        if(request()->isPost()){
            $data=input('post.');
            $sort=$data['sort'];
            $order=$data['order'];
            $page=$data['page'];
            $rows=$data['rows'];

            $where=[];
            foreach($data as $k =>$v){
                if(preg_match('/search_(.*)/',$k,$match)){
                    $where[$match[1]]=['like','%'.$v.'%'];
                }
            }

            $res=[
                'total'=>0,
                'rows'=>[]
            ];
            if(count($where)>0){
                $res['total']=$this->db->where($where)->count();
                $res['rows']=$this->db->where($where)->order($sort,$order)->limit($rows)->page($page)->select();
            }else{
                $res['total']=$this->db->count();
                $res['rows']=$this->db->order($sort,$order)->limit($rows)->page($page)->select();
            }
            return $res;
        }
        //return json_encode(Admin::select());
        return view();
    }


    public function add(){
        if(request()->isPost()){
            $res=$this->db->add(input('post.'));
            savelogs('添加角色');
            return json_encode($res);
        }
        return view();
    }
    //修改
    public function edit(){
        if(request()->isPost()){
            $res=$this->db->edit(input('post.'));

            savelogs('编辑角色');
            return json_encode($res);
        }
        $id=request()->get('id');
        if($id){
            $data=$this->db->find($id);
            $this->assign('data',$data);
        }
        return view();
    }

    //删除
    public function remove(){
        if(request()->isPost()){
            $res=$this->db->del(input('post.'));
            savelogs('删除角色');
            return json_encode($res);
        }
    }
}
