<?php

namespace app\admin\controller;

use app\admin\model\Hook as HookModel;

class Hook extends Common
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new HookModel();
        $this->vname="钩子";
        $this->vid="hook";
    }

    public function index(){
        if(request()->isPost()) {
            $data=input('post.');
            $map = $this->getMap($data);
            $order = $this->getOrder($data);
            // 数据列表
            $res['total'] = $this->db->where($map)->order($order)->limit($data['rows'])->page($data['page'])->count();
            $res['rows'] = $this->db->where($map)->order($order)->limit($data['rows'])->page($data['page'])->select();

            return $res;
        }
        return view();
    }


    public function add(){
        if(request()->isPost()){
            $data=input('post.');
            $res=$this->db->add($data);

            if($res['status']==200){
                savelogs('添加'.$this->vname,$data['name']);
            }else{
                savelogs('添加'.$this->vname,$data['name'].' 失败');
            }

            return json_encode($res);
        }
        return view();
    }
    //修改
    public function edit(){
        if(request()->isPost()){
            $data=input('post.');
            $res=$this->db->edit($data);

            if($res['status']==200){
                savelogs('编辑'.$this->vname,$data['name'].' id:'.$data['id']);
            }else{
                savelogs('编辑'.$this->vname,$data['name'].' id:'.$data['id'].' 失败');
            }
            return json_encode($res);
        }
        $id=request()->get('id');
        if($id){
            $data=$this->db->find($id);
            $this->assign('data',$data);
        }
        return view();
    }
    //删除
    public function remove(){
        if(request()->isPost()){
            $data=input('post.');
            $res=$this->db->del($data);
            if($res['status']==200){
                savelogs('删除'.$this->vname,' id:'.implode(',',$data['id']));
            }else{
                savelogs('删除'.$this->vname,' id:'.implode(',',$data['id']).' 失败');
            }
            return json_encode($res);
        }
    }
}
