<?php

namespace app\admin\controller;

use think\Request;
use \app\admin\model\Log as Logs;

class Log extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new Logs();
    }

    public function index(){
        if(request()->isPost()){
            $data=input('post.');
            $sort=$data['sort'];
            $order=$data['order'];
            $page=$data['page'];
            $rows=$data['rows'];

            $where=[];
            foreach($data as $k =>$v){
                if(preg_match('/search_(.*)/',$k,$match)){
                    $where[$match[1]]=['like','%'.$v.'%'];
                }
            }

            $res=[
                'total'=>0,
                'rows'=>[]
            ];
            if(count($where)>0){
                $res['total']=$this->db->where($where)->count();
                $res['rows']=$this->db->where($where)->field('password',true)->order($sort,$order)->limit($rows)->page($page)->select();
            }else{
                $res['total']=$this->db->count();
                $res['rows']=$this->db->field('password',true)->order($sort,$order)->limit($rows)->page($page)->select();
            }
            return $res;
        }
        return view();
    }
}
