<?php

namespace app\admin\controller;

use app\common\model\Admin;
use app\common\model\AuthGroup;
use app\common\model\AuthGroupAccess;

class Manager extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new Admin();
    }

    public function index(){
        if(request()->isPost()){
            $data=input('post.');
            $sort=$data['sort'];
            $order=$data['order'];
            $page=$data['page'];
            $rows=$data['rows'];

            $where=[];
            foreach($data as $k =>$v){
                if(preg_match('/search_(.*)/',$k,$match)){
                    $where[$match[1]]=['like','%'.$v.'%'];
                }
            }

            $res=[
                'total'=>0,
                'rows'=>[]
            ];
            if(count($where)>0){
                $res['total']=$this->db->where($where)->count();
                $res['rows']=$this->db->where($where)->field('password',true)->order($sort,$order)->limit($rows)->page($page)->select();
            }else{
                $res['total']=$this->db->count();
                $res['rows']=$this->db->field('password',true)->order($sort,$order)->limit($rows)->page($page)->select();
            }
            return $res;
        }
        //return json_encode(Admin::select());
        return view();
    }

    //修改管理员密码
    public function pass(){
        if(request()->isPost()){
            $res=$this->db->pass(input('post.'));
            if($res['status']==200){
                session(null);
            }
            savelogs('修改密码');
            return json_encode($res);
        }
        return view();
    }

    public function add(){
        if(request()->isPost()){
            $res=$this->db->add(input('post.'));

            savelogs('添加管理员');
            return json_encode($res);
        }
        return view();
    }

    //修改
    public function edit(){
        if(request()->isPost()){
            $res=$this->db->edit(input('post.'));

            savelogs('编辑管理员');
            return json_encode($res);
        }
        $id=request()->get('id');
        if($id){
            $data=$this->db->find($id);
            $data=$data->hidden(['password'])->toArray();
            $this->assign('data',$data);
        }
        return view();
    }

    public function remove(){
        if(request()->isPost()){
            $res=$this->db->del(input('post.'));
            savelogs('删除管理员');
            return json_encode($res);
        }
    }

    //授权
    public function access(){
        if(request()->isPost()){
            $res=$this->db->access(input('post.'));
            return json_encode($res);
        }
        $id=request()->get('id');
        if($id){
            $user=$this->db->find($id);
            $data=$user->hidden(['password'])->toArray();
            //return $data['group_id']=$user->authGroup;
            $this->assign('data',$data);
        }
        return view();
    }

    public function group(){
        $access=AuthGroupAccess::where('uid',input('post.id'))->field('group_id')->select();
        $gids=[];
        foreach($access as $v){
            $gids[]=$v['group_id'];
        }
        $group=AuthGroup::where('status',1)->order('id','asc')->select();
        foreach($group as $v){
            if(in_array($v['id'],$gids)){
                $v['selected']=true;
            }
        }
        return $group;
    }
}
