<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
    [
        'title'       => '门户',
        'type'    => 1,
        'name'   => 'cms/index/index',
        'showed' => 1,
        'sort'        => 100,
        'child'       => [
            [
                'title'       => '常用操作',
                'type'    => 1,
                'name'   => '',
                'showed' => 1,
                'sort'        => 100,
                'child'       => [
                    [
                        'title'       => '仪表盘',
                        'type'    => 1,
                        'name'   => 'cms/index/index',
                        'showed' => 1,
                        'sort'        => 100,
                    ],
                    [
                        'title'       => '发布文档',
                        'type'    => 1,
                        'name'   => 'cms/document/add',
                        'showed' => 1,
                        'sort'        => 100,
                    ],
                    [
                        'title'       => '文档列表',
                        'type'    => 1,
                        'name'   => 'cms/document/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/document/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/document/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/document/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/document/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/document/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                    [
                        'title'       => '单页管理',
                        'type'    => 1,
                        'name'   => 'cms/page/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/page/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/page/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/page/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/page/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/page/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/page/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                    [
                        'title'       => '回收站',
                        'type'    => 1,
                        'name'   => 'cms/recycle/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/recycle/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '还原',
                                'type'    => 1,
                                'name'   => 'cms/recycle/restore',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title'       => '内容管理',
                'type'    => 1,
                'name'   => '',
                'showed' => 1,
                'sort'        => 100,
                'child'       => [],
            ],
            [
                'title'       => '营销管理',
                'type'    => 1,
                'name'   => '',
                'showed' => 1,
                'sort'        => 100,
                'child'       => [
                    [
                        'title'       => '广告管理',
                        'type'    => 1,
                        'name'   => 'cms/advert/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/advert/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/advert/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/advert/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/advert/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/advert/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/advert/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '广告分类',
                                'type'    => 1,
                                'name'   => 'cms/advert_type/index',
                                'showed' => 1,
                                'sort'        => 100,
                                'child'       => [
                                    [
                                        'title'       => '新增',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/add',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/edit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '删除',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/delete',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '启用',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/enable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '禁用',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/disable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '快速编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/advert_type/quickedit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                ],
                            ],
                        ],
                    ],
                    [
                        'title'       => '滚动图片',
                        'type'    => 1,
                        'name'   => 'cms/slider/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/slider/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/slider/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/slider/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/slider/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/slider/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/slider/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                    [
                        'title'       => '友情链接',
                        'type'    => 1,
                        'name'   => 'cms/link/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/link/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/link/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/link/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/link/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/link/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/link/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                    [
                        'title'       => '客服管理',
                        'type'    => 1,
                        'name'   => 'cms/support/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/support/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/support/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/support/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/support/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/support/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/support/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title'       => '门户设置',
                'type'    => 1,
                'name'   => '',
                'showed' => 1,
                'sort'        => 100,
                'child'       => [
                    [
                        'title'       => '栏目分类',
                        'type'    => 1,
                        'name'   => 'cms/column/index',
                        'online_hide' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/column/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/column/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/column/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/column/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/column/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/column/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                    [
                        'title'       => '内容模型',
                        'type'    => 1,
                        'name'   => 'cms/model/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/model/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/model/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/model/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/model/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/model/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/model/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '字段管理',
                                'type'    => 1,
                                'name'   => 'cms/field/index',
                                'showed' => 1,
                                'sort'        => 100,
                                'child'       => [
                                    [
                                        'title'       => '新增',
                                        'type'    => 1,
                                        'name'   => 'cms/field/add',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/field/edit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '删除',
                                        'type'    => 1,
                                        'name'   => 'cms/field/delete',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '启用',
                                        'type'    => 1,
                                        'name'   => 'cms/field/enable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '禁用',
                                        'type'    => 1,
                                        'name'   => 'cms/field/disable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '快速编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/field/quickedit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                ],
                            ],
                        ],
                    ],
                    [
                        'title'       => '导航管理',
                        'type'    => 1,
                        'name'   => 'cms/nav/index',
                        'showed' => 1,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'type'    => 1,
                                'name'   => 'cms/nav/add',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'type'    => 1,
                                'name'   => 'cms/nav/edit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'type'    => 1,
                                'name'   => 'cms/nav/delete',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'type'    => 1,
                                'name'   => 'cms/nav/enable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'type'    => 1,
                                'name'   => 'cms/nav/disable',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '快速编辑',
                                'type'    => 1,
                                'name'   => 'cms/nav/quickedit',
                                'showed' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '菜单管理',
                                'type'    => 1,
                                'name'   => 'cms/menu/index',
                                'showed' => 1,
                                'sort'        => 100,
                                'child'       => [
                                    [
                                        'title'       => '新增',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/add',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/edit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '删除',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/delete',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '启用',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/enable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '禁用',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/disable',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                    [
                                        'title'       => '快速编辑',
                                        'type'    => 1,
                                        'name'   => 'cms/menu/quickedit',
                                        'showed' => 1,
                                        'sort'        => 100,
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
